import NavbarComponent from "@/components/NavbarComponent";
import "./globals.css";
import SidebarComponent from "@/components/SidebarComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        <section className="flex justify-between">
          <div className="w-[20%]">
            <SidebarComponent />
          </div>
          <div className="w-[78%]">
            <NavbarComponent />
          </div>
        </section>
        {children}
      </body>
    </html>
  );
}
